// setup-env.js — Auto-generate .env if missing
// Run: node setup-env.js
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const envPath = path.join(__dirname, '.env');

if (fs.existsSync(envPath)) {
    console.log('✅ .env already exists — skipping');
    process.exit(0);
}

const jwtSecret = crypto.randomBytes(64).toString('hex');
const encryptionKey = crypto.randomBytes(16).toString('hex');

const envContent = `# Auto-generated by setup-env.js — ${new Date().toISOString()}
PORT=3001
NODE_ENV=development
JWT_SECRET=${jwtSecret}
CREDENTIAL_ENCRYPTION_KEY=${encryptionKey}
DEFAULT_ADMIN_PASSWORD=admin123
CORS_ORIGIN=http://localhost:3001
LOG_LEVEL=debug
`;

fs.writeFileSync(envPath, envContent);
console.log('✅ .env created with secure random secrets');
console.log('⚠️  Change DEFAULT_ADMIN_PASSWORD before production use!');
